esphome:
  name: esp32c6
  friendly_name: esp32c6
  platformio_options:
    board: "esp32-c6-devkitc-1"
    framework: "arduino"
    platform: https://github.com/platformio/platform-espressif32.git#develop
    lib_deps:
      - "https://github.com/ESP32Async/AsyncTCP.git"
      - "https://github.com/ESP32Async/ESPAsyncWebServer.git"
    lib_extra_dirs:
      - ".esphome\\build\\espnibe\\.piolibdeps\\AsyncTCP-esphome\\"
      - ".esphome\\build\\espnibe\\.piolibdeps\\ESPAsyncWebserver-esphome\\"
    lib_ignore:
      - "AsyncTCP-esphome"
      - "ESPAsyncWebServer-esphome"
    lib_ldf_mode: deep
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
      - framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip
    
    build_flags:
     - -D ARDUINO_USB_MODE=1
     - -D USE_LOGGER_USB_SERIAL_JTAG=1

esp32:
  board: esp32-c3-devkitc-1
  flash_size: 4MB
  variant: ESP32C6
  framework:
    type: arduino   

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: "randomPass"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails. Change the password to something more secure.
  ap:
    ssid: "Esphome-Web-ESP32-C6"
    password: "randomPass"

captive_portal:

output:
  # Heartbeat status LED, change GPIO pin as needed
  - platform: gpio
    id: statusLED
    pin: GPIO19

interval:
  - interval: 1000ms
    then:
      - output.turn_on: statusLED
      - delay: 500ms
      - output.turn_off: statusLED


